apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: demoapp-httpproxy
spec:
  virtualhost:
    fqdn: demoapp.orcunuso.io
  routes:
  - conditions:
    - header:
        name: appversion
        contains: green
    services:
    - name: demoapp-green-service
      port: 8080
  - services:
    - name: demoapp-red-service
      port: 8080
